package it.cnr.istc.stlab.mira.commons;

import org.openrdf.model.URI;
import org.openrdf.model.impl.URIImpl;

/**
 * Vocabulary definitions from /Users/andrea/Documents/CNR/ANVUR/Ontologie/qualification_process.rdf 
 * @author Auto-generated by schemagen on 02 Oct 2017 11:19 
 */
public class QualificationProcessOntology {
    
	/** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://w3id.org/anvur/nq/ontology/";
    
    /** <p>The namespace of the data as a string</p> */
    public static final String NS_DATA = "http://w3id.org/anvur/nq/data/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a URI</p> */
    public static final URI NAMESPACE = new URIImpl( NS );
    
    public static final URI NAMESPACE_DATA = new URIImpl( NS_DATA );
    
    public static final URI birthDate = new URIImpl( "http://w3id.org/anvur/nq/ontology/birthDate" );
    
    public static final URI hasCitationCountType = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasCitationCountType" );

    public static final URI hasCitationCount = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasCitationCount" );
    
    public static final URI hasSource = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasSource" );
    
    public static final URI content = new URIImpl( "http://w3id.org/anvur/nq/ontology/content" );
    
    public static final URI description = new URIImpl( "http://w3id.org/anvur/nq/ontology/description" );
    
    public static final URI doi = new URIImpl( "http://w3id.org/anvur/nq/ontology/doi" );
    
    public static final URI duringQualificaitonRound = new URIImpl( "http://w3id.org/anvur/nq/ontology/duringQualificaitonRound" );
    
    public static final URI endTime = new URIImpl( "http://w3id.org/anvur/nq/ontology/endTime" );
    
    public static final URI familyName = new URIImpl( "http://w3id.org/anvur/nq/ontology/familyName" );
    
    public static final URI firstElement = new URIImpl( "http://w3id.org/anvur/nq/ontology/firstElement" );
    
    public static final URI forApplication = new URIImpl( "http://w3id.org/anvur/nq/ontology/forApplication" );
    
    public static final URI forQualificationRound = new URIImpl( "http://w3id.org/anvur/nq/ontology/forQualificationRound" );
    
    public static final URI givenName = new URIImpl( "http://w3id.org/anvur/nq/ontology/givenName" );
    
    public static final URI hasAuthor = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasAuthor" );
    
    public static final URI hasBibliographicItemType = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasBibliographicItemType" );
    
    public static final URI hasCharacteristic = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasCharacteristic" );
    
    /** <p>The object URI that enables relations between qualification processes 
     *  and committees.La object URI tra un processo di abilitazione (HabilitationCall) 
     *  e un comitato.</p>
     */
    public static final URI hasCommittee = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasCommittee" );
    
    /** <p>La relazione che permette di rappresentare le persone come membri di una commissione 
     *  di valutazione.The membership relation between people and committees.</p>
     */
    public static final URI hasCommitteeMember = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasCommitteeMember" );
    
    public static final URI hasDocument = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasDocument" );
    
    public static final URI hasDocumentType = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasDocumentType" );
    
    public static final URI hasJudgment = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasJudgment" );
    
    public static final URI hasPart = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasPart" );
    
    public static final URI hasPublications = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasPublications" );
    
    /** <p>The object URI that connects a qualification round to a qualification 
     *  level.La object URI che connette una tornata di abilitazione ad un livello 
     *  di abilitazione.</p>
     */
    public static final URI hasQualificationLevel = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasQualificationLevel" );
    
    public static final URI hasHabilitationCall = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasHabilitationCall" );
    
    public static final URI hasQualificationRound = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasQualificationRound" );
    
    /** <p>The object URI that relates a HabilitationCall to a QualificationRound.La 
     *  object URI che collega un processo di abilitazione (HabilitationCall) 
     *  ad una tornata di abilitazione (QualificationRound).</p>
     */
    public static final URI hasRound = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasRound" );
    
    public static final URI hasScore = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasScore" );
    
    /** <p>La object URI che associa una candidatura ad un'opera, che, in questo 
     *  caso, rappresenta un 'opera scelta' dalla persona che sottomette la candidatura.The 
     *  object URI that associates an application with a work, which represents 
     *  a selected work for the person submitting the application.</p>
     */
    public static final URI hasSelectedPublications = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasSelectedPublications" );
    
    public static final URI hasSubEvaluation = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasSubEvaluation" );
    
    public static final URI hasUnitOfMeasure = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasUnitOfMeasure" );
    
    public static final URI hasQualification = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasQualification" );
    
    public static final URI hasQualificationType = new URIImpl( "http://w3id.org/anvur/nq/ontology/hasQualificationType" );
    
    public static final URI isApplicationOf = new URIImpl( "http://w3id.org/anvur/nq/ontology/isApplicationOf" );
    
    public static final URI isCommitteeMemberOf = new URIImpl( "http://w3id.org/anvur/nq/ontology/isCommitteeMemberOf" );
    
    public static final URI isCommitteeOf = new URIImpl( "http://w3id.org/anvur/nq/ontology/isCommitteeOf" );
    
    public static final URI isDocumentOf = new URIImpl( "http://w3id.org/anvur/nq/ontology/isDocumentOf" );
    
    /** <p>La object URI che connette un livello di abilitazione ad una tornata 
     *  di abilitazione.The object URI that connects a qualification level to 
     *  a qualification round.</p>
     */
    public static final URI isQualificationLevelOf = new URIImpl( "http://w3id.org/anvur/nq/ontology/isQualificationLevelOf" );
    
    /** <p>Object URI inversa di hasRound (ha tornata) che permette di collegare 
     *  una tornata di abilitazione ad un processo di abilitazione.Inverse object 
     *  URI of hasRound that relates a qualification round to a qualification 
     *  process.</p>
     */
    public static final URI isRoundOf = new URIImpl( "http://w3id.org/anvur/nq/ontology/isRoundOf" );
    
    public static final URI isSelectedWorkOf = new URIImpl( "http://w3id.org/anvur/nq/ontology/isSelectedWorkOf" );
    
    public static final URI isbn = new URIImpl( "http://w3id.org/anvur/nq/ontology/isbn" );
    
    public static final URI issn = new URIImpl( "http://w3id.org/anvur/nq/ontology/issn" );
    
    public static final URI title = new URIImpl( "http://w3id.org/anvur/nq/ontology/title" );
    
    public static final URI year = new URIImpl( "http://w3id.org/anvur/nq/ontology/year" );
    
    public static final URI authorString = new URIImpl( "http://w3id.org/anvur/nq/ontology/authorString" );
    
    public static final URI label = new URIImpl( "http://w3id.org/anvur/nq/ontology/label" );
    
    public static final URI forQualificaitonLevel = new URIImpl( "http://w3id.org/anvur/nq/ontology/forQualificaitonLevel" );
    
    public static final URI forSubjectArea = new URIImpl( "http://w3id.org/anvur/nq/ontology/forSubjectArea" );
    
    public static final URI lastElement = new URIImpl( "http://w3id.org/anvur/nq/ontology/lastElement" );
    
    public static final URI name = new URIImpl( "http://w3id.org/anvur/nq/ontology/name" );
    
    public static final URI nextElement = new URIImpl( "http://w3id.org/anvur/nq/ontology/nextElement" );
    
    public static final URI refers = new URIImpl( "http://w3id.org/anvur/nq/ontology/refers" );
    
    public static final URI scoreValue = new URIImpl( "http://w3id.org/anvur/nq/ontology/scoreValue" );
    
    public static final URI startTime = new URIImpl( "http://w3id.org/anvur/nq/ontology/startTime" );
    
    /** <p>CandidaturaAn application to a qualification round.ApplicationUna candidatura 
     *  ad una tornata di abilitaizone.</p>
     */
    public static final URI Application = new URIImpl( "http://w3id.org/anvur/nq/ontology/Application" );
    
    public static final URI BibliographicItem = new URIImpl( "http://w3id.org/anvur/nq/ontology/BibliographicItem" );
    
    public static final URI BibliographicItemType = new URIImpl( "http://w3id.org/anvur/nq/ontology/BibliographicItemType" );
    
    public static final URI Characteristic = new URIImpl( "http://w3id.org/anvur/nq/ontology/Characteristic" );
    
    public static final URI CitationCount = new URIImpl( "http://w3id.org/anvur/nq/ontology/CitationCount" );
    
    public static final URI CitationCountType = new URIImpl( "http://w3id.org/anvur/nq/ontology/CitationCountType" );
    
    public static final URI Source = new URIImpl( "http://w3id.org/anvur/nq/ontology/Source" );
    
    /** <p>A committee that evaluates the applications for a qualification process.Un 
     *  comitato che valuta le candidature ad un processo di abilazione.</p>
     */
    public static final URI Committee = new URIImpl( "http://w3id.org/anvur/nq/ontology/Committee" );
    
    public static final URI CurriculumVitae = new URIImpl( "http://w3id.org/anvur/nq/ontology/CurriculumVitae" );
    
    public static final URI Document = new URIImpl( "http://w3id.org/anvur/nq/ontology/Document" );
    
    public static final URI DocumentPart = new URIImpl( "http://w3id.org/anvur/nq/ontology/DocumentPart" );
    
    public static final URI DocumentType = new URIImpl( "http://w3id.org/anvur/nq/ontology/DocumentType" );
    
    public static final URI Evaluation = new URIImpl( "http://w3id.org/anvur/nq/ontology/Evaluation" );
    
    public static final URI Judgment = new URIImpl( "http://w3id.org/anvur/nq/ontology/Judgment" );
    
    /** <p>Una persona.A person.</p> */
    public static final URI Person = new URIImpl( "http://w3id.org/anvur/nq/ontology/Person" );
    
    /** <p>Il livello professionale, ex. professore ordinario (prima fascia), professore 
     *  associato (seconda fascia), etc. Il livello professionale è tipicamente associato 
     *  a livelli professionali specifici.The professional level, e.g. full professor, 
     *  associate professor, etc. Qualification processes are typically associated 
     *  with speficic professional levels.</p>
     */
    public static final URI QualificationLevel = new URIImpl( "http://w3id.org/anvur/nq/ontology/QualificationLevel" );
    
    /** <p>A qualification process.Un processo di abilitazione.</p> */
    public static final URI HabilitationCall = new URIImpl( "http://w3id.org/anvur/nq/ontology/HabilitationCall" );
    
    /** <p>A qualification round during wich a committee evaluates a set of applications 
     *  for the qualification to a subject area with a specific level. The round is 
     *  belong to a qualification process.Una tornata di abilitazione durante la quale 
     *  un comitato valuta una serie di candidature per l'abilitazione ad livello 
     *  di uno specifico settore disciplinare.</p>
     */
    public static final URI QualificationRound = new URIImpl( "http://w3id.org/anvur/nq/ontology/QualificationRound" );
    
    public static final URI ReferenceList = new URIImpl( "http://w3id.org/anvur/nq/ontology/ReferenceList" );
    
    public static final URI Score = new URIImpl( "http://w3id.org/anvur/nq/ontology/Score" );
    
    /** <p>The subject area associated with a qualification process.Il settore disciplinare 
     *  associabile ad un processo di abilitazione.</p>
     */
    public static final URI SubjectArea = new URIImpl( "http://w3id.org/anvur/nq/ontology/SubjectArea" );
    
    public static final URI Qualification = new URIImpl( "http://w3id.org/anvur/nq/ontology/Qualification" );
    
    public static final URI QualificationType = new URIImpl( "http://w3id.org/anvur/nq/ontology/QualificationType" );
    
    public static final URI QualificationList = new URIImpl( "http://w3id.org/anvur/nq/ontology/QualificationList" );
    
    public static final URI UnitOfMeasure = new URIImpl( "http://w3id.org/anvur/nq/ontology/UnitOfMeasure" );
    
    public static final URI Publication = new URIImpl( "http://w3id.org/anvur/nq/ontology/Publication" );
    
}
